# Generated by Django 6.0 on 2026-01-15 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeedamman', '0002_movie_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('preferred_date', models.DateField(default=django.utils.timezone.now)),
                ('preferred_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
