# Generated by Django 6.0 on 2026-01-15 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeedamman', '0003_testdrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(choices=[('LS6', 'LS6'), ('LS8', 'LS8')], max_length=10)),
                ('package', models.CharField(max_length=50)),
                ('exterior', models.CharField(max_length=50)),
                ('interior', models.CharField(max_length=50)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
