# Generated by Django 6.0 on 2026-01-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeedamman', '0006_alter_carconfiguration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
