# Generated by Django 6.0.1 on 2026-01-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeedamman', '0008_alter_carconfiguration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carconfiguration',
            name='package',
            field=models.CharField(choices=[('2WD - Premium', '2WD - Premium'), ('4WD - Ultra Premium', '4WD - Ultra Premium')], max_length=50),
        ),
    ]
