# Generated by Django 6.0.1 on 2026-01-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightspeedamman', '0009_alter_carconfiguration_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carconfiguration',
            name='exterior',
            field=models.CharField(choices=[('Metallic Champagne', 'Metallic Champagne'), ('Aurora', 'Aurora'), ('Snow White', 'Snow White'), ('Graphite Black', 'Graphite Black')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carconfiguration',
            name='interior',
            field=models.CharField(choices=[('Crimson', 'Crimson'), ('Elegant Black', 'Elegant Black'), ('Off-White', 'Off-White')], max_length=50),
        ),
    ]
